version: '3.8'

services:
  pz-server-gateway:
    image: ghcr.io/pz-stories/pz-server-gateway:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8088:8088"
    environment:
      EXPRESS_PORT: 8080
      WEBSOCKET_PORT: 8088
      ZOMBOID_PATH: "/Zomboid"
      EXPORTED_PLAYERS_DB: "/data/exportedPlayers.db"
      PZ_PLAYERS_DB: "/Zomboid/Saves/Multiplayer/pzserver/players.db"
    volumes:
      - "${ZOMBOID_PATH:-~/Zomboid}:/Zomboid"
      - exported_data:/data/


volumes:
  exported_data:
